language: objective-c
osx_image: xcode8.1
rvm: 2.2.2
before_install:
- |
    gem install cocoapods -v '1.0.1' --no-rdoc --no-ri --no-document --quiet
    gem install xcpretty -N --no-ri --no-rdoc
    pod repo update 
script:
- ./Scripts/build.sh