version: 2

jobs:
  test-ios10.3:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Update Dependencies
          command: ./Scripts/update_dependencies.sh
      - run:
          name: Run tests on iOS 10.3
          command: ./Scripts/test.sh

  test-ios11.1:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Update Dependencies
          command: ./Scripts/update_dependencies.sh
      - run:
          name: Run tests on iOS 11.0
          command: ./Scripts/test.sh

workflows:
  version: 2
  test-ios10.3:
    jobs:
      - test-ios10.3
  test-ios11.1:
    jobs:
      - test-ios11.1

