version: 2

jobs:
  lint:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Update Dependencies
          command: ./Scripts/update_dependencies.sh
      - run:
          name: Lint
          command: swiftlint

  test-ipad-ios10.3:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Update Dependencies
          command: ./Scripts/update_dependencies.sh
      - run:
          name: Run tests on iPad iOS 10.3
          command: ./Scripts/test-10.3-ipad.sh

  test-iphone-ios10.3:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Update Dependencies
          command: ./Scripts/update_dependencies.sh
      - run:
          name: Run tests on iPhone iOS 10.3
          command: ./Scripts/test-10.3-iphone.sh

  test-ipad-ios11.0:
      macos:
        xcode: "9.0"
      steps:
        - checkout
        - run:
            name: Update Dependencies
            command: ./Scripts/update_dependencies.sh
        - run:
            name: Run tests on iPad iOS 11.0
            command: ./Scripts/test-11.0-ipad.sh

  test-iphone-ios11.0:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Update Dependencies
          command: ./Scripts/update_dependencies.sh
      - run:
          name: Run tests on iPhone iOS 11.0
          command: ./Scripts/test-11.0-iphone.sh
      - run:
          name: Codecov
          command: bash <(curl -s https://codecov.io/bash) -J 'Rocket.Chat'

workflows:
  version: 2
  build-and-test:
    jobs:
      - lint
      - test-iphone-ios11.0:
          requires:
            - lint
      - test-iphone-ios10.3:
          requires:
            - lint
      - test-ipad-ios10.3:
          requires:
            - lint
      - test-ipad-ios11.0:
          requires:
            - lint
  
