codecov:
  branch: develop
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2 
  round: down
  range: 70...100
  ignore:  
    - "Rocket.ChatTests/"

  status:
    project: yes
    patch: no
    changes: no

comment:
  layout: "header, diff, changes"
  behavior: default
