codecov:
  branch: develop
  bot: null
  ci: null
  strict_yaml_branch: null
  max_report_age: null
  notify:
    after_n_builds: null
    countdown: null
    require_ci_to_pass: yes
  archive:
    uploads: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null
        base: auto
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: null
        flags: null
        paths: null

    changes:
      default:
        branches: null
        base: auto
        set_pending: yes
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: null
        flags: null
        paths: null